name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: coveralls tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout pcb2gcode source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: show env twice?  no
      run: |
        env
        echo "::set-env name=NODE_COVERALLS_DEBUG::1"
        echo ${{ secrets.GITHUB_TOKEN }} | sed 's/1/ /'
    - name: Upload coverage to coveralls
      id: my_upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: pcb2gcode-lcov.info
    - name: Upload coverage to coveralls again
      id: my_upload2
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: pcb2gcode-lcov.info
    - name: show the coveralls output
      continue-on-error: true
      run: |
        echo here is the result
        echo '${{ steps.my_upload.outputs.coveralls-api-result }}'
    - name: show the coveralls output2
      continue-on-error: true
      run: |
        echo here is the result
        echo '${{ steps.my_upload2.outputs.coveralls-api-result }}'
